---
#
# Configure Server Profiles
#
# The hosts group used is provided by the group variable or defaulted to 'Intersight_Servers'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME_Demo
#

- name: Configure Server Profile
  cisco.intersight.intersight_server_profile:
    api_private_key: "{{ api_private_key }}"
    api_key_id: "{{ api_key_id }}"
    name: SP-Server1
    target_platform: FIAttached
    tags:
      - Key: Site
        Value: SJC02
    description: Profile for Server1
 #   boot_order_policy: COS-Boot
 #   imc_access_policy: sjc02-d23-access
 #   lan_connectivity_policy: sjc02-d23-lan
 #   local_user_policy: guest-admin
 #   ntp_policy: lab-ntp
 #   storage_policy: storage
 #   virtual_media_policy: COS-VM
